<a href="https://colab.research.google.com/github/Supreme-YS/ML/blob/main/201204_Hidden_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. 과거의 데이터 준비
# 2. 모델 구조를 만든다
# 3. 모델을 학습시킨다.
# 4. 모델을 사용한다.

파일경로(보스턴) = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'

파일경로(아이리스) = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

보스턴 집값 예측

In [2]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [6]:
model.summary() # 13 --> 10 --> 1개의 출력

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [5]:
# 3. 데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs = 1000, verbose=0) # 멀티레이어 학습

In [7]:
# 4. 모델 이용하기
print(model.predict(독립[:5]))
print(종속[:5])

[[29.66684 ]
 [25.084816]
 [30.533316]
 [31.109293]
 [30.806545]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


아이리스 품종분류


In [9]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd


In [10]:

###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)
 
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

(150, 4) (150, 3)


In [11]:
# 모델 구조 확인
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [12]:
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0205 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9961 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9799 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9648 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9508 - accuracy: 0.3400
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9364 - accuracy: 0.3600
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9222 - accuracy: 0.4067
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9078 - accuracy: 0.5333
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8932 - accuracy: 0.5867
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8784 - accuracy: 0.6267
Epoch 11/100
5/5 [===========

In [13]:
 
###########################
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[0.87672335 0.11113297 0.01214375]
 [0.87590486 0.11252895 0.01156628]
 [0.87618744 0.11204775 0.01176477]
 [0.8746615  0.1152271  0.01011133]
 [0.8769309  0.11121464 0.01185447]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
