<a href="https://colab.research.google.com/github/Supreme-YS/ML/blob/main/pre_processing_ml%5B03%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

학습목표
- 데이터 인코딩 -> 라벨인코딩, 원-핫-인코딩
- 정규화, 표준화 -> 피처 스케일링
- 결측치 처리 및 이상치 처리

In [1]:
# 데이터 인코딩 - 라벨 인코딩 : 문자열을 숫자로 변환하는 작업
# fit(), transform()
from sklearn.preprocessing import LabelEncoder

In [14]:
item_label = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(item_label)
digit_label = encoder.transform(item_label)

print('encoder :', encoder)
print('encoder result : ', digit_label)
print('*'*50)

print('decoder result : ', encoder.inverse_transform(digit_label))
print('type', type(digit_label))

encoder : LabelEncoder()
encoder result :  [0 1 4 5 3 3 2 2]
**************************************************
decoder result :  ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']
type <class 'numpy.ndarray'>


In [9]:
# 데이터 인코딩 - One-hot Encoding : 고유값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [20]:
item_label = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(item_label)
digit_label = encoder.transform(item_label)

print('type', type(digit_label))

# 2차원 데이터 변환
digit_label = digit_label.reshape(-1,1)
print( digit_label.shape , digit_label)

# one-hot 인코딩
one_hot_encoder = OneHotEncoder()
one_hot_encoder.fit(digit_label)
one_hot_label = one_hot_encoder.transform(digit_label)

print( one_hot_label.shape)
print( one_hot_label.toarray())


type <class 'numpy.ndarray'>
(8, 1) [[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
(8, 6)
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [23]:
# 판다스 원핫인코딩
labelDF = pd.DataFrame({'item' : ['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

pd.get_dummies(labelDF)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0